on:
  workflow_dispatch:

jobs:
  build:
    name: Lets go now
    runs-on: ubuntu-latest
    steps:
      - name: Get date
        run: date
      - name: Get secret
        env:
          MYSECRET: ${{ secrets.TESTSECRET }}
        run: echo ${{ secrets.TESTSECRET }} >secret.tmp; cat secret.tmp
      - name: Check Disk Space
        run: df -h
      - name: Docker login
        run: echo '${{ secrets.DHTOK }}' | docker login --username dladams --password-stdin
