on:
  workflow_dispatch:

jobs:
  build:
    name: Lets go now
    runs-on: ubuntu-latest
    env:
    
    steps:
      - shell: bash

      - name: Get date
        run: date
      - name: Get secret
        env:
          MYSECRET: ${{ secrets.TESTSECRET }}
        run: echo Secret is $MYSECRET
      - name: Check Disk Space
        run: df -h
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username dladams --password-stdin
